{% set name = "moz-sql-parser" %}
{% set version = "4.40.21126" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3d37cc8ff118d86009aa12646791549537ec0ae8ac312efd4641289c8eee080

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mo-dots 4.22.21108
    - mo-future 3.147.20327
    - mo-logs 4.23.21108

test:
  imports:
    - moz_sql_parser
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/klahnakoski/moz-sql-parser
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Extract Parse Tree from SQL

extra:
  recipe-maintainers:
    - xhochy
